baseurl = "https://zombase.netlify.com/"
languageCode = "en-us"
title = "Zombase"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmarkdown$", "_files$", "_cache$"]
coverImage = "images/zombase.png"
customCSS = ["css/main.css"]



[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/gongcastro/Zombase"
    weight = 3
[[menu.main]]
    name = "CV"
    url = "/vitae/"
    weight = 4
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5


[params]
    description = "Zombies, RStats, and some actual research on developmental psycholinguistics"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

[params.logo]
    url = "logo.png"
    width = 10
    height = 10
    alt = "Logo"

