---
title: The impact of COVID-19 on "zombie" Twitter
author: Gonzalo García-Castro
date: '2020-03-27'
slug: the-impact-of-covid-19-on-zombie-twitter
draft: true
categories:
  - post
  - zombies
tags:
  - twitter
  - stats
  - COVID-19
---


```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

# load packages
library(rtweet) # for retrieving data
library(dplyr)
library(tidyr)
library(ggplot2)



```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

## retrieve data
tweets_zombies <- search_tweets(
  "#zombies",
  n = 10000,
  include_rts = FALSE, 
  type = "recent", 
) %>%
	mutate(hashtag = "#zombies")

tweets_cv <- search_tweets(
  "#coronavirus",
  n = 10000,
  include_rts = FALSE, 
  type = "recent", 
) %>%
	mutate(hashtag = "#coronavirus")

tweets <- bind_rows(tweets_zombies, tweets_cv)

```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

ggplot(tweets, aes(x = created_at)) +
	facet_wrap(~hashtag, scales = "free_y") +
	geom_density(fill = "grey", alpha = 0.5) +
	labs(x = "Date", y = "Counts",
		 title = "No. of tweets including '#zombies'") +
	theme(
		panel.background = element_rect(fill = "transparent"),
		panel.border = element_rect(fill = "transparent"),
		panel.grid = element_line(colour = "grey", linetype = "dotted"),
		plot.background = element_rect(fill = "transparent", colour = "transparent"),
		text = element_text(size = 12, colour = "black"),
		axis.text = element_text(colour = "black")
	)

```