---
title: 'Active communities of zombie-lovers: Where are you?'
author: Gonzalo García-Castro
date: '2020-04-01'
draft: true
slug: active-communities-of-zombie-lovers-where-are-you
categories: []
tags:
  - Zombdata
  - dataviz
  - rstats
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = FALSE,
	include = FALSE
)
```


```{r prepare, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}

# load packages
library(magrittr)
library(dplyr)
library(tidyr)
library(purrr)
library(stringr)
library(forcats)
library(ggplot2)
library(maps)
library(googlesheets4)
library(sysfonts)
library(gganimate)
library(ggthemes)
library(here)

# get credentials
options(
	gargle_oauth_cache = ".secrets",
	gargle_oauth_email = "zombdata@gmail.com"
)

sheets_auth(
	token = readRDS(here("static", "credentials", "google_token.rds")),
	cache = ".secrets/",
	email = "zombdata@gmail.com",
	scopes = "https://www.googleapis.com/auth/spreadsheets"
)

# load fonts
font_add_google("Bangers", "bangers")
fira <- font_add_google("Fira Sans Condensed", "fira")

# load data
zombdata <- sheets_read("1NScfQetZxxVcX5hlrTU-37yd-Pdm86As0f6q78884Z8")

```


The aim of this post if to provide a first glimpse into what Zombdata looks like. We will focus on describing the spatial location of the main sources of zombie-related material. The analysis here presented are updated every day!

# Where are the creators?

```{r fig_map, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

world <- map_data("world")
cities <- world.cities %>% select(name, country, pop, lat_city, long_city) %>% as_tibble()
	
data <- zombdata %>%
	rename_all(str_to_lower) %>%
	group_by(country) %>%
	arrange(country, year) %>%
	mutate(score = 1,
		   counts = cumsum(lag(score, default = 0) + 1),
		   country = factor(country, levels = unique(.$country[order(counts)]))
		   ) %>%
	ungroup()


data %>%
	ggplot(aes(x = country, y = log(counts))) +
	geom_bar(stat = "identity", width = 0.5) +
	labs(x = "Country", y = "Counts", title = "Year") +
	coord_flip() +
	transition_time(year, range = c(min(data$year, na.rm = TRUE), max(data$year, na.rm = TRUE))) +
	ease_aes("linear")
	


ggplot(data = data) +
	borders("world", colour = "gray85", fill = "gray80") +
	geom_point(data = cities, aes(x = long_city, y = lat_city)) 
	labs(title = "Geospatial location of zombie-related material creators",
		 subtitle = "Films, TV shows, videgames, etc. are piled up.",
		 fill = "Counts (Log scale)") +
	theme(
		panel.grid = element_blank(),
		panel.background = element_rect(fill = "black"),
		plot.background = element_rect(fill = "black"),
		text = element_text(family = "fira", colour = "white"),
		axis.text = element_blank(),
		axis.line = element_blank(),
		axis.ticks = element_blank(),
		panel.border = element_blank(),
		axis.title = element_blank(),
		legend.position = c(0.1, 0.4),
		legend.background = element_rect(fill = "black", colour = "black")
	) +

	




ggsave(here("static", "images", "post_2020-03-19_map.png"))


```
